name: continuous-integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Checkout java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Lint
        run: make lint
      - name: Build
        run: make build
      - name: Install
        run: make install
