name: continuous-integration

on: push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'coretto'
          java-version: '21'

      - run: make lint
      - run: make build
      - run: make install
